name: Push docker image

on:
  workflow_dispatch:
    branches: [main]

jobs:
  push-to-acr:
    
    defaults:
      run:
        shell: bash
        working-directory: ./python

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: floapp001acr.azurecr.io
          username: ${{ secrets.AZURE_AD_CLIENT_ID }}
          password: ${{ secrets.AZURE_AD_CLIENT_SECRET }}

      - name: Build Docker image
        run: |
          docker build -t floapp001 .

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag floapp001 floapp001acr.azurecr.io/floapp001:latest
          docker push -a floapp001acr.azurecr.io/floapp001