name: Push docker image

on:
  workflow_dispatch:
    branches: [main]

jobs:
  push-to-acr:

    defaults:
      run:
        shell: bash
        working-directory: ./python

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: streamiotacr.azurecr.io
          username: ${{ secrets.AZURE_AD_CLIENT_ID }}
          password: ${{ secrets.AZURE_AD_CLIENT_SECRET }}

      - name: Build Docker image
        run: |
          docker build -t streamiot .

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag streamiot streamiotacr.azurecr.io/streamiot:latest
          docker push -a streamiotacr.azurecr.io/streamiot
